name: Control Push
on: push

jobs:
  qa:
    name: Check tests and linting
    runs-on: ubuntu-22.04  # Version plus récente
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Run linting
        run: flake8 .

      - name: Run tests
        run: pytest
